units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 5
  py: ky + 5
  # "Double" Padding Variables
  dpx: kx + 9
  dpy: ky + 9
  # M2 Screw Inserts
  screwSize: 1.5
  standoffSize: 2.5
points:
  key:
    padding: 1ky
    spread: 1kx
  zones:
    matrix:
      anchor:
        rotate: 4
        shift: [50, -100]
      columns:
        pinky:
          key.column_net: P031
        ring:
          key.stagger: 5
          key.splay: -4
          key.origin: [-12, -19]
          key.column_net: P029
        middle:
          key.stagger: 2.5
          key.column_net: P002
        index:
          key.stagger: -2.5
          key.column_net: P115
        inner:
          key.stagger: -2.5
          key.column_net: P113
        extras:
          rows.bottom.skip: true
          key.column_net: P111
      rows:
        bottom:
          row_net: P024
        home:
          row_net: P100
        top:
          row_net: P009
        num:
          row_net: P010
    thumbfanbottom:
      anchor:
        ref: matrix_inner_bottom
        shift: [0, -19]
      columns:
        near:
          key.splay: -5
          key.column_net: P106
        home:
          key.spread: 20
          key.splay: -40
          key.origin: [-10.5, -7]
          key.column_net: P104
        far:
          key.spread: 22
          key.splay: -40
          key.origin: [-11, -4]
          key.column_net: P011
      rows:
        thumbbottom:
          row_net: P024
    thumbfanupper:
      anchor:
        ref: matrix_extras_home
        shift: [4, -21]
      columns:
        near:
          key.splay: -18
          key.column_net: P106
        home:
          key.spread: 22
          key.splay: -35
          key.origin: [-12, -6]
          key.column_net: P104
        far:
          key.spread: 22
          key.splay: -30
          key.origin: [-12, -6]
          key.column_net: P011
      rows:
        thumbupper:
          row_net: P100
  mirror:
    ref: thumbfanupper_far_thumbupper
    distance: 50
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
      fillet: 0
  keys:
    - what: rectangle
      where: true
      size: [kx - 0.5, ky - 0.5]
      fillet: 0
  board_left:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_pinky_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_ring_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_num
          shift: [0.5px, 0.5py]
        - ref: matrix_extras_num
          shift: [1.5px, 0.5py]
        - ref: matrix_extras_home
          shift: [1.5px, -0.5py]
        - ref: thumbfanupper_home_thumbupper
          shift: [0.5px, 0.5py]
        - ref: thumbfanupper_far_thumbupper
          shift: [-0.5px, 0.5py]
        - ref: thumbfanupper_far_thumbupper
          shift: [0.5px, 0.5py]
        - ref: thumbfanbottom_far_thumbbottom
          shift: [0.5px, 0.5py]
        - ref: thumbfanbottom_far_thumbbottom
          shift: [0.5px, -0.5py]
        - ref: thumbfanbottom_far_thumbbottom
          shift: [-0.5kx, -0.5py]
        - ref: thumbfanbottom_near_thumbbottom
          shift: [0.5kx, -0.5py]
        - ref: thumbfanbottom_near_thumbbottom
          shift: [-0.5px, -0.5py]
        - ref: matrix_inner_bottom
          shift: [-0.5px, -0.5py]
        - ref: matrix_index_bottom
          shift: [-0.5px, -0.5py]
        - ref: matrix_ring_bottom
          shift: [0.5px, -0.5py]
        - ref: matrix_pinky_bottom
          shift: [0.5px, -0.5py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px, -0.5py]
  board_right:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: mirror_matrix_pinky_num
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_ring_num
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_middle_num
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_middle_num
          shift: [0.5px, 0.5py]
        - ref: mirror_matrix_extras_num
          shift: [1.5px, 0.5py]
        - ref: mirror_matrix_extras_home
          shift: [1.5px, -0.5py]
        - ref: mirror_thumbfanupper_home_thumbupper
          shift: [0.5px, 0.5py]
        - ref: mirror_thumbfanupper_far_thumbupper
          shift: [-0.5px, 0.5py]
        - ref: mirror_thumbfanupper_far_thumbupper
          shift: [0.5px, 0.5py]
        - ref: mirror_thumbfanbottom_far_thumbbottom
          shift: [0.5px, 0.5py]
        - ref: mirror_thumbfanbottom_far_thumbbottom
          shift: [0.5px, -0.5py]
        - ref: mirror_thumbfanbottom_far_thumbbottom
          shift: [-0.5kx, -0.5py]
        - ref: mirror_thumbfanbottom_near_thumbbottom
          shift: [0.5kx, -0.5py]
        - ref: mirror_thumbfanbottom_near_thumbbottom
          shift: [-0.5px, -0.5py]
        - ref: mirror_matrix_inner_bottom
          shift: [-0.5px, -0.5py]
        - ref: mirror_matrix_index_bottom
          shift: [-0.5px, -0.5py]
        - ref: mirror_matrix_ring_bottom
          shift: [0.5px, -0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [0.5px, -0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [-0.5px, -0.5py]

  # Create a slightly larger version of board_left/board_right for the case so that it can have room to go around the PCB
  xl_board_left:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_pinky_num
          shift: [-0.5dpx, 0.5dpy]
        - ref: matrix_ring_num
          shift: [-0.5dpx, 0.5dpy]
        - ref: matrix_middle_num
          shift: [-0.5dpx, 0.5dpy]
        - ref: matrix_middle_num
          shift: [0.5dpx, 0.5dpy]
        - ref: matrix_extras_num
          shift: [1.4dpx, 0.5dpy]
        - ref: matrix_extras_home
          shift: [1.4dpx, -0.5dpy]
        - ref: thumbfanupper_home_thumbupper
          shift: [0.5dpx, 0.5dpy]
        - ref: thumbfanupper_far_thumbupper
          shift: [-0.5dpx, 0.5dpy]
        - ref: thumbfanupper_far_thumbupper
          shift: [0.5dpx, 0.5dpy]
        - ref: thumbfanbottom_far_thumbbottom
          shift: [0.5dpx, 0.5dpy]
        - ref: thumbfanbottom_far_thumbbottom
          shift: [0.5dpx, -0.5dpy]
        - ref: thumbfanbottom_far_thumbbottom
          shift: [-0.5kx, -0.5dpy]
        - ref: thumbfanbottom_near_thumbbottom
          shift: [0.5kx, -0.5dpy]
        - ref: thumbfanbottom_near_thumbbottom
          shift: [-0.5dpx, -0.5dpy]
        - ref: matrix_inner_bottom
          shift: [-0.5dpx, -0.5dpy]
        - ref: matrix_index_bottom
          shift: [-0.5dpx, -0.5dpy]
        - ref: matrix_ring_bottom
          shift: [0.5dpx, -0.5dpy]
        - ref: matrix_pinky_bottom
          shift: [0.5dpx, -0.5dpy]
        - ref: matrix_pinky_bottom
          shift: [-0.5dpx, -0.5dpy]
  xl_board_right:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: mirror_matrix_pinky_num
          shift: [-0.5dpx, 0.5dpy]
        - ref: mirror_matrix_ring_num
          shift: [-0.5dpx, 0.5dpy]
        - ref: mirror_matrix_middle_num
          shift: [-0.5dpx, 0.5dpy]
        - ref: mirror_matrix_middle_num
          shift: [0.5dpx, 0.5dpy]
        - ref: mirror_matrix_extras_num
          shift: [1.4dpx, 0.5dpy]
        - ref: mirror_matrix_extras_home
          shift: [1.4dpx, -0.5dpy]
        - ref: mirror_thumbfanupper_home_thumbupper
          shift: [0.5dpx, 0.5dpy]
        - ref: mirror_thumbfanupper_far_thumbupper
          shift: [-0.5dpx, 0.5dpy]
        - ref: mirror_thumbfanupper_far_thumbupper
          shift: [0.5dpx, 0.5dpy]
        - ref: mirror_thumbfanbottom_far_thumbbottom
          shift: [0.5dpx, 0.5dpy]
        - ref: mirror_thumbfanbottom_far_thumbbottom
          shift: [0.5dpx, -0.5dpy]
        - ref: mirror_thumbfanbottom_far_thumbbottom
          shift: [-0.5kx, -0.5dpy]
        - ref: mirror_thumbfanbottom_near_thumbbottom
          shift: [0.5kx, -0.5dpy]
        - ref: mirror_thumbfanbottom_near_thumbbottom
          shift: [-0.5dpx, -0.5dpy]
        - ref: mirror_matrix_inner_bottom
          shift: [-0.5dpx, -0.5dpy]
        - ref: mirror_matrix_index_bottom
          shift: [-0.5dpx, -0.5dpy]
        - ref: mirror_matrix_ring_bottom
          shift: [0.5dpx, -0.5dpy]
        - ref: mirror_matrix_pinky_bottom
          shift: [0.5dpx, -0.5dpy]
        - ref: mirror_matrix_pinky_bottom
          shift: [-0.5dpx, -0.5dpy]
  xl_board_left_key_cutouts:
    - name: xl_board_left
    - operation: subtract
      name: keys
  xl_board_right_key_cutouts:
    - name: xl_board_right
    - operation: subtract
      name: keys

  # TODO: Do I need these?
  _left_combo:
    - name: board_left
    - operation: subtract
      name: keys
  left_mounting:
    - what: circle
      radius: screwSize
      where:
        ref: [matrix_pinky_num]
        shift: [0.5px, 0.55ky]
    - what: circle
      radius: screwSize
      where:
        ref: [matrix_ring_bottom]
        shift: [-0.35kx, -0.52py]
    - what: circle
      radius: screwSize
      where:
        ref: [thumbfanbottom_far_thumbbottom]
        shift: [0.3kx, 0.55py]
    - what: circle
      radius: screwSize
      where:
        ref: [matrix_extras_home]
        shift: [1px, 0]
  left_standoff:
    - what: circle
      radius: standoffSize
      where:
        ref: [matrix_pinky_num]
        shift: [0.5px, 0.55ky]
    - what: circle
      radius: standoffSize
      where:
        ref: [matrix_ring_bottom]
        shift: [-0.35kx, -0.52py]
    - what: circle
      radius: standoffSize
      where:
        ref: [thumbfanbottom_far_thumbbottom]
        shift: [0.3kx, 0.55py]
    - what: circle
      radius: standoffSize
      where:
        ref: [matrix_extras_home]
        shift: [1px, 0]
pcbs:
  left:
    outlines:
      main:
        outline: board_left
    footprints:
      keyswitches:
        what: choc
        where: /^(matrix_|thumbfanupper_|thumbfanbottom_).*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: /^(matrix_|thumbfanupper_|thumbfanbottom_).*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      # Controller
      nice_nano:
        what: nice_nano
        params:
          orientation: down
        where:
          ref: matrix_extras_num
          shift: [kx + 3, -0.48 * ky]
          rotate: -90
      # Battery Jack
      jstph:
        what: jstph
        where:
          ref: matrix_extras_home
          shift: [kx, 0.4 * ky]
          rotate: -90
        params:
          side: B
          pos: pos
          neg: GND
      # Reset switch (horizontal community version)
      horizontal_reset:
        what: EVQPUC
        params:
          side: B
          from: GND
          to: RST
        where:
          ref: matrix_extras_home
          shift: [1.8 * kx, 0.25 * ky]
          rotate: -90
      # Battery on/off switch
      battery_switch:
        what: slider
        where:
          ref: matrix_extras_home
          shift: [1.8 * kx, -0.25 * ky]
          rotate: -90
        params:
          side: B
          from: pos
          to: RAW
      # Mounting Holes
      hole_top_left:
        what: mountinghole
        where:
          ref: [matrix_pinky_num]
          shift: [0.5px, -0.1ky]
      hole_bottom_left:
        what: mountinghole
        where:
          ref: [matrix_ring_bottom]
          shift: [-0.52kx, 0.5ky]
      hole_bottom_right:
        what: mountinghole
        where:
          ref: [thumbfanbottom_far_thumbbottom]
          shift: [-0.75kx, 0.4ky]
      hole_middle_right:
        what: mountinghole
        where:
          ref: [matrix_extras_home]
          shift: [1.3kx, 0.4ky]
      hole_center:
        what: mountinghole
        where:
          ref: [matrix_middle_top]
          shift: [0.5kx, -0.4ky]
  right:
    outlines:
      main:
        outline: board_right
    footprints:
      keyswitches:
        what: choc
        where: /^mirror_.*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: /^mirror_.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      # Controller
      nice_nano:
        what: nice_nano
        params:
          orientation: down
        where:
          ref: mirror_matrix_extras_num
          shift: [kx + 3, -0.48 * ky]
          rotate: 90
      # Battery Jack
      jstph:
        what: jstph
        where:
          ref: mirror_matrix_extras_home
          shift: [kx, 0.4 * ky]
          rotate: -90
        params:
          side: B
          pos: pos
          neg: GND
      # Reset switch (horizontal community version)
      horizontal_reset:
        what: EVQPUC
        params:
          side: B
          from: GND
          to: RST
        where:
          ref: mirror_matrix_extras_home
          shift: [1.8 * kx, 0.25 * ky]
          rotate: -90
      # Battery on/off switch
      battery_switch:
        what: slider
        where:
          ref: mirror_matrix_extras_home
          shift: [1.8 * kx, -0.25 * ky]
          rotate: -90
        params:
          side: B
          from: pos
          to: RAW
      # Mounting Holes
      hole_top_left:
        what: mountinghole
        where:
          ref: [mirror_matrix_pinky_num]
          shift: [0.5px, -0.1ky]
      hole_bottom_left:
        what: mountinghole
        where:
          ref: [mirror_matrix_ring_bottom]
          shift: [-0.52kx, 0.5ky]
      hole_bottom_right:
        what: mountinghole
        where:
          ref: [mirror_thumbfanbottom_far_thumbbottom]
          shift: [-0.75kx, 0.4ky]
      hole_middle_right:
        what: mountinghole
        where:
          ref: [mirror_matrix_extras_home]
          shift: [1.3kx, 0.4ky]
      hole_center:
        what: mountinghole
        where:
          ref: [mirror_matrix_middle_top]
          shift: [0.5kx, -0.4ky]
cases:
  bottom:
    - name: board_left
      extrude: 1
  xlBottom:
    - name: xl_board_left
      extrude: 1
  _outerWall:
    - name: xl_board_left
      extrude: 5.6
  _innerWall:
    - name: board_left
      extrude: 5.6
  wall:
    - what: case
      name: _outerWall
      operation: add
    - what: case
      name: _innerWall
      operation: subtract
  _holes:
    - name: left_mounting
      extrude: 4
  _standoffs:
    - name: left_standoff
      extrude: 4
  case:
    - what: case
      name: _standoffs
      operation: add
    - what: case
      name: _holes
      operation: subtract
    - what: case
      name: xlBottom
      operation: add
    - what: case
      name: wall
      operation: add
