units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 5
  py: ky + 5
  # M2 Screw Inserts
  screwThreadSize: 2
  standoffSize: 4.0
  # Choc Switch Size
  chocW: 14
  chocH: 14
  # Nice Nano 2 Measurements
  nanoW: 18.5
  nanoH: 33.5
  nanoT: 3.2
  # Case Measurements
  casePadding: 1.5
  caseThickness: 9
points:
  key:
    padding: 1ky
    spread: 1kx
  zones:
    matrix:
      anchor:
        rotate: 4
        shift: [50, -100]
      columns:
        pinky:
          key.column_net: P031
        ring:
          key.stagger: 5
          key.splay: -4
          key.origin: [-12, -19]
          key.column_net: P029
        middle:
          key.stagger: 2.5
          key.column_net: P002
        index:
          key.stagger: -2.5
          key.column_net: P115
        inner:
          key.stagger: -2.5
          key.column_net: P113
        extras:
          rows.bottom.skip: true
          key.column_net: P111
      rows:
        bottom:
          row_net: P024
        home:
          row_net: P100
        top:
          row_net: P009
        num:
          row_net: P010
    thumbfanbottom:
      anchor:
        ref: matrix_inner_bottom
        shift: [3, -19]
      columns:
        near:
          key.splay: -10
          key.column_net: P106
        home:
          key.spread: 20
          key.splay: -20
          key.origin: [-10.5, -5]
          key.column_net: P104
        far:
          key.spread: 22
          key.splay: -20
          key.origin: [-11, 0]
          key.column_net: P011
      rows:
        thumbbottom:
          row_net: P024
    thumbfanupper:
      anchor:
        ref: matrix_extras_home
        shift: [3, -20]
      columns:
        near:
          key.splay: -15
          key.column_net: P106
        home:
          key.spread: 22
          key.splay: -20
          key.origin: [-11, 0]
          key.column_net: P104
        far:
          key.spread: 22
          key.splay: -20
          key.origin: [-11, 0]
          key.column_net: P011
      rows:
        thumbupper:
          row_net: P100
  mirror:
    ref: thumbfanupper_far_thumbupper
    distance: 50
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
      fillet: 0
  keys:
    - what: rectangle
      where: true
      size: [chocW, chocH]
      fillet: 0
  board_left:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_pinky_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_ring_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_num
          shift: [0.5px, 0.5py]
        - ref: matrix_extras_num
          shift: [1.5px, 0.5py]
        - ref: matrix_extras_home
          shift: [1.5px, -0.5py]
        - ref: thumbfanupper_far_thumbupper
          shift: [-0.5px, 0.5py]
        - ref: thumbfanupper_far_thumbupper
          shift: [0.5px, 0.5py]
        - ref: thumbfanbottom_far_thumbbottom
          shift: [0.5px, 0.5py]
        - ref: thumbfanbottom_far_thumbbottom
          shift: [0.5px, -0.5py]
        - ref: thumbfanbottom_far_thumbbottom
          shift: [-0.5kx, -0.5py]
        - ref: thumbfanbottom_near_thumbbottom
          shift: [0.5kx, -0.5py]
        - ref: thumbfanbottom_near_thumbbottom
          shift: [-0.5px, -0.5py]
        - ref: matrix_inner_bottom
          shift: [-0.5px, -0.5py]
        - ref: matrix_index_bottom
          shift: [-0.5px, -0.5py]
        - ref: matrix_ring_bottom
          shift: [0.5px, -0.5py]
        - ref: matrix_pinky_bottom
          shift: [0.5px, -0.5py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px, -0.5py]
  board_right:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: mirror_matrix_pinky_num
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_ring_num
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_middle_num
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_middle_num
          shift: [0.5px, 0.5py]
        - ref: mirror_matrix_extras_num
          shift: [1.5px, 0.5py]
        - ref: mirror_matrix_extras_home
          shift: [1.5px, -0.5py]
        - ref: mirror_thumbfanupper_far_thumbupper
          shift: [-0.5px, 0.5py]
        - ref: mirror_thumbfanupper_far_thumbupper
          shift: [0.5px, 0.5py]
        - ref: mirror_thumbfanbottom_far_thumbbottom
          shift: [0.5px, 0.5py]
        - ref: mirror_thumbfanbottom_far_thumbbottom
          shift: [0.5px, -0.5py]
        - ref: mirror_thumbfanbottom_far_thumbbottom
          shift: [-0.5kx, -0.5py]
        - ref: mirror_thumbfanbottom_near_thumbbottom
          shift: [0.5kx, -0.5py]
        - ref: mirror_thumbfanbottom_near_thumbbottom
          shift: [-0.5px, -0.5py]
        - ref: mirror_matrix_inner_bottom
          shift: [-0.5px, -0.5py]
        - ref: mirror_matrix_index_bottom
          shift: [-0.5px, -0.5py]
        - ref: mirror_matrix_ring_bottom
          shift: [0.5px, -0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [0.5px, -0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [-0.5px, -0.5py]

  # Create a slightly larger version of board_left/board_right for the case so that it can have room to go around the PCB
  xl_board_left:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_pinky_num
          shift: [-0.5px - casePadding, 0.5py + casePadding]
        - ref: matrix_ring_num
          shift: [-0.5px - casePadding, 0.5py + casePadding]
        - ref: matrix_middle_num
          shift: [-0.5px, 0.5py + casePadding]
        - ref: matrix_middle_num
          shift: [0.5px, 0.5py + casePadding]
        - ref: matrix_extras_num
          shift: [1.5px + casePadding, 0.5py + casePadding]
        - ref: matrix_extras_home
          shift: [1.5px + casePadding, -0.5py]
        - ref: thumbfanupper_far_thumbupper
          shift: [-0.5px, 0.5py + casePadding]
        - ref: thumbfanupper_far_thumbupper
          shift: [0.5px + casePadding, 0.5py + casePadding]
        - ref: thumbfanbottom_far_thumbbottom
          shift: [0.5px + casePadding, 0.5py + casePadding]
        - ref: thumbfanbottom_far_thumbbottom
          shift: [0.5px + casePadding, -0.5py - casePadding]
        - ref: thumbfanbottom_far_thumbbottom
          shift: [-0.5kx, -0.5py - casePadding]
        - ref: thumbfanbottom_near_thumbbottom
          shift: [0.5kx, -0.5py - casePadding]
        - ref: thumbfanbottom_near_thumbbottom
          shift: [-0.5px - casePadding, -0.5py - casePadding]
        - ref: matrix_inner_bottom
          shift: [-0.5px - casePadding, -0.5py - casePadding]
        - ref: matrix_index_bottom
          shift: [-0.5px, -0.5py - casePadding]
        - ref: matrix_ring_bottom
          shift: [0.5px, -0.5py - casePadding]
        - ref: matrix_pinky_bottom
          shift: [0.5px, -0.5py - casePadding]
        - ref: matrix_pinky_bottom
          shift: [-0.5px - casePadding, -0.5py - casePadding]
  _xl_board_left_key_cutouts:
    - name: xl_board_left
    - operation: subtract
      name: keys
  _left_mounting:
    - what: circle
      radius: screwThreadSize
      where:
        ref: [matrix_ring_num]
        shift: [-0.5px, -0.5ky]
    - what: circle
      radius: screwThreadSize
      where:
        ref: [matrix_ring_bottom]
        shift: [-0.5kx, -0.5py]
    - what: circle
      radius: screwThreadSize
      where:
        ref: [thumbfanbottom_far_thumbbottom]
        shift: [-0.45px, -0.25ky]
    - what: circle
      radius: screwThreadSize
      where:
        ref: [matrix_extras_home]
        shift: [1.3kx, 0.4ky]
    - what: circle
      radius: screwThreadSize
      where:
        ref: [matrix_index_top]
        shift: [0.48kx, 0.5ky]
  xl_board_left_keys_mounting_cutouts:
    - name: _xl_board_left_key_cutouts
    - operation: subtract
      name: _left_mounting
pcbs:
  left:
    outlines:
      main:
        outline: board_left
    footprints:
      keyswitches:
        what: choc
        where: /^(matrix_|thumbfanupper_|thumbfanbottom_).*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: /^(matrix_|thumbfanupper_|thumbfanbottom_).*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      # Controller
      nice_nano:
        what: nice_nano
        params:
          orientation: up
        where:
          ref: matrix_extras_num
          shift: [kx + 3, -0.48 * ky]
          rotate: -90
      # Battery Jack
      jstph:
        what: jstph
        where:
          ref: matrix_extras_home
          shift: [kx, 0.4 * ky]
          rotate: -90
        params:
          side: B
          pos: pos
          neg: GND
      # Reset switch (horizontal community version)
      horizontal_reset:
        what: EVQPUC
        params:
          side: B
          from: GND
          to: RST
        where:
          ref: matrix_extras_home
          shift: [1.8 * kx, 0.25 * ky]
          rotate: -90
      # Battery on/off switch
      battery_switch:
        what: slider
        where:
          ref: matrix_extras_home
          shift: [1.8 * kx, -0.28 * ky]
          rotate: -90
        params:
          side: B
          from: pos
          to: RAW
      # Mounting Holes
      hole_top_left:
        what: mountinghole
        where:
          ref: [matrix_ring_num]
          shift: [-0.5px, -0.5ky]
      hole_bottom_left:
        what: mountinghole
        where:
          ref: [matrix_ring_bottom]
          shift: [-0.5kx, -0.5py]
      hole_bottom_right:
        what: mountinghole
        where:
          ref: [thumbfanbottom_far_thumbbottom]
          shift: [-0.45px, -0.25ky]
      hole_middle_right:
        what: mountinghole
        where:
          ref: [matrix_extras_home]
          shift: [1.3kx, 0.4ky]
      hole_center:
        what: mountinghole
        where:
          ref: [matrix_index_top]
          shift: [0.48kx, 0.5ky]
  right:
    outlines:
      main:
        outline: board_right
    footprints:
      keyswitches:
        what: choc
        where: /^mirror_.*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: /^mirror_.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      # Controller
      nice_nano:
        what: nice_nano
        params:
          orientation: up
        where:
          ref: mirror_matrix_extras_num
          shift: [kx + 3, -0.48 * ky]
          rotate: 90
      # Battery Jack
      jstph:
        what: jstph
        where:
          ref: mirror_matrix_extras_home
          shift: [kx, 0.4 * ky]
          rotate: -90
        params:
          side: B
          pos: pos
          neg: GND
      # Reset switch (horizontal community version)
      horizontal_reset:
        what: EVQPUC
        params:
          side: B
          from: GND
          to: RST
        where:
          ref: mirror_matrix_extras_home
          shift: [1.8 * kx, 0.25 * ky]
          rotate: -90
      # Battery on/off switch
      battery_switch:
        what: slider
        where:
          ref: mirror_matrix_extras_home
          shift: [1.8 * kx, -0.28 * ky]
          rotate: -90
        params:
          side: B
          from: pos
          to: RAW
      # Mounting Holes
      hole_top_left:
        what: mountinghole
        where:
          ref: [mirror_matrix_ring_num]
          shift: [-0.5px, -0.5ky]
      hole_bottom_left:
        what: mountinghole
        where:
          ref: [mirror_matrix_ring_bottom]
          shift: [-0.5kx, -0.5py]
      hole_bottom_right:
        what: mountinghole
        where:
          ref: [mirror_thumbfanbottom_far_thumbbottom]
          shift: [-0.45px, -0.25ky]
      hole_middle_right:
        what: mountinghole
        where:
          ref: [mirror_matrix_extras_home]
          shift: [1.3kx, 0.4ky]
      hole_center:
        what: mountinghole
        where:
          ref: [mirror_matrix_index_top]
          shift: [0.48kx, 0.5ky]
cases:
  top_plate:
    - name: xl_board_left_keys_mounting_cutouts
      extrude: 1.2
